version: "3.9"

services:
  nginx:
    container_name: nginx2
    build: ./nginx/
    ports:
      - 8888:80
      # - 8333:443 #if need ssl
    volumes:
      - ./code/public:/srv/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm

  phpfpm:
    container_name: phpfpm2
    build: ./php/
    volumes:
      - ./code:/srv/www
      - ./php/configs:/usr/local/etc/php/conf.d
  
  mysql:
    container_name: mysql2
    image: mysql:latest
    ports:
      - 3333:3306
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
